.PHONY: all clean run pack build-pre build-post

all: build-pre run build-post	
	
build-post: 

run: 
	@cd verify && ./run_all.sh ..

pack:
	rm -f alf.zip
	zip -r alf.zip verify/ Makefile.checker\
		README.md 

clean:
	rm -rf verify/output/
